apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug-container
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: my-pvc
      mountPath: /mnt
  volumes:
  - name: my-pvc
    persistentVolumeClaim:
      claimName: lbl-appen-prod-obsfs-pvc
