apiVersion: v1
kind: Service
metadata:
  name: pe-process-main-svc
spec:
  selector:
    app: pe-process-main
  ports:
  - name: pe-process-main-port
    protocol: TCP
    port: 5010
    targetPort: 5010
  type: NodePort
