apiVersion: apps/v1
kind: Deployment
metadata:
  name: pe-redis
spec:
  selector:
    matchLabels:
      app: pe-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: pe-redis
    spec:
      containers:
      - name: pe-redis
        image: redis:7.0.10-bullseye
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
